ifneq (,$(filter udp_stress,$(USEMODULE)))

LWIP ?= 0

USEMODULE += netdev_default
ifeq (0,$(LWIP))
	USEMODULE += auto_init_gnrc_netif
	# USEMODULE += gnrc_ipv6_default
	USEMODULE += gnrc_ipv6_router_default
else
	USEMODULE += lwip_ipv6 # idk if this is needed really
endif

USEMODULE += netutils
USEMODULE += sema_inv
USEMODULE += sock_udp
USEMODULE += xtimer

USEMODULE += shell_cmds_default
USEMODULE += shell_cmd_gnrc_udp

# Routing
USEMODULE += gnrc_rpl
USEMODULE += auto_init_gnrc_rpl

USEMODULE += ps
USEMODULE += netstats_l2
USEMODULE += netstats_ipv6
USEMODULE += netstats_rpl

endif
