ifneq (,$(filter udp_multihop,$(USEMODULE)))

# # Include packages that pull up and auto-init the link layer.
# # NOTE: 6LoWPAN will be included if IEEE802.15.4 devices are present
# USEMODULE += netdev_default
# USEMODULE += auto_init_gnrc_netif
# # Activate ICMPv6 error messages
# USEMODULE += gnrc_icmpv6_error
# # Specify the mandatory networking module for a IPv6 routing node
# # USEMODULE += gnrc_ipv6_default
# USEMODULE += gnrc_ipv6_router_default
# # Add a routing protocol
# USEMODULE += gnrc_rpl
# USEMODULE += auto_init_gnrc_rpl
# # Additional networking modules that can be dropped if not needed
# USEMODULE += gnrc_icmpv6_echo
# USEMODULE += shell_cmd_gnrc_udp
# # Add also the shell, some shell commands
# USEMODULE += shell
# USEMODULE += shell_cmds_default
# USEMODULE += ps
# USEMODULE += netstats_l2
# USEMODULE += netstats_ipv6
# USEMODULE += netstats_rpl

USEMODULE += netdev_default
USEMODULE += auto_init_gnrc_netif
USEMODULE += gnrc_ipv6_router_default 
USEMODULE += gnrc_icmpv6 #
USEMODULE += gnrc_icmpv6_echo # 
USEMODULE += gnrc_ndp # Neighbor Discovery Protocol
USEMODULE += gnrc_rpl
USEMODULE += auto_init_gnrc_rpl


endif
